//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekanatWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DekanatDBEntities1 : DbContext
    {
        public DekanatDBEntities1()
            : base("name=DekanatDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<група> група { get; set; }
        public virtual DbSet<предмет> предмет { get; set; }
        public virtual DbSet<розклад> розклад { get; set; }
        public virtual DbSet<спеціальність> спеціальність { get; set; }
        public virtual DbSet<студент> студент { get; set; }
        public virtual DbSet<факультет> факультет { get; set; }
    }
}
