//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekanatWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class група
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public група()
        {
            this.студент = new HashSet<студент>();
        }


        [Display(Name = "Номер групи")]
        public int GroupId { get; set; }

        [RegularExpression(@"[0-9]{2}[1-9]{1}-[0-9]{2}-[1-9]{1}$", ErrorMessage = "Введіть назву групи у форматі 121-19-1")]
        [Display(Name = "Назва групи")]
        public string назва { get; set; }

        [Display(Name = "Номер спеціальності")]
        public int SpecialtyId { get; set; }
    
        public virtual спеціальність спеціальність { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<студент> студент { get; set; }
    }
}
