//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekanatWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class група
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public група()
        {
            this.студент = new HashSet<студент>();
        }
    
        public int GroupId { get; set; }
        public string назва { get; set; }
        public int SpecialtyId { get; set; }
    
        public virtual спеціальність спеціальність { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<студент> студент { get; set; }
    }
}
