//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekanatWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class розклад
    {
        public int CurriculumId { get; set; }
        public int курс { get; set; }
        public int семестр { get; set; }
        public int лекційні_часи { get; set; }
        public int практичні_часи { get; set; }
        public int лабораторні_часи { get; set; }
        public string форма_захисту { get; set; }
        public string курсова_робота { get; set; }
        public int курсові_часи { get; set; }
        public int SpecialtyId { get; set; }
        public int SubjectId { get; set; }
    
        public virtual предмет предмет { get; set; }
        public virtual спеціальність спеціальність { get; set; }
    }
}
