//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekanatWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class студент
    {
        public int StudentId { get; set; }
        public string імя { get; set; }
        public string прізвище { get; set; }
        public string телефон { get; set; }
        public int GroupId { get; set; }
        public Nullable<System.DateTime> дата_народження { get; set; }
    
        public virtual група група { get; set; }
    }
}
